IMP: al seleccionar comuna, llenar campos de pais, estado y ciudad
dansanti/l10n_cl_fe pull request #27
Opened 2018-02-07 23:33 UTC by celm1990

commplementario al commit 92a2c05e199f9d1e1e0421ed2a2d79cbfb0e4977 y 1174b2834f98d77001e74c19f0f14b3e18589957

2018-02-07 23:35 UTC, celm1990 commented
Como mensionas en [el comentario ](https://github.com/dansanti/l10n_cl_fe/issues/3#issuecomment-355135465), se agrego que al seleccionar la comuna, se llene el estado y el pais automaticamente, para facilitar el ingreso de datos por parte del usuario. Por favor revisar y hacer merge

2018-02-14 21:09 UTC, celm1990 commented
Podrias revisar este PR por favor y hacer el merge???

2018-02-15 00:37 UTC, dansanti requested changes

2018-02-15 00:37 UTC, dansanti commented on models/res_partner.py
> +        else:
En el caso de que deseleccione qno quiere decir que se ponga todo en false

2018-02-20 21:36 UTC, celm1990 commented on models/res_partner.py
> +        else:
Es mas bien para decirle al usuario que debe seleccionar una comuna, que no quede vacia, igual si se borra los datos, al volver a seleccionar la comuna se llenarian de nuevo, no veo cual podria ser el problema???

2018-02-27 03:32 UTC, dansanti commented on models/res_partner.py
> +        else:
el problema es que la gente tendía que llenarlo de nuevo

2018-02-27 03:37 UTC, celm1990 commented on models/res_partner.py
> +        else:
Te pediria que pruebes el cambio, cuando seleccionas una comuna se llenan todos los campos, si x alguna razon se borra la comuna, si se borran los datos pero al volver a seleccionar otra vez la comuna se vuelven a llenar los datos, asi que no entiendo el problema, Por eso el campo de comuna esta entre los primeros, para q sea seleccionado al inicio y los demas se autocompleten.

2018-06-04 21:38 UTC, celm1990 commented
@dansanti se procedio a realizar el cambio solicitado, al borrar la comuna no se borren los datos de provincia, ciudad y pais.

Por favor verificar que todo este correcto y hacer merge.

2018-06-04 21:47 UTC, celm1990 commented
Se hizo rebase de la rama, y se realizo el cambio solicitado. Espero que aceptes el PR, ya que algo similar espero hacer en el punto de venta. Que al seleccionar la comuna se llene automaticamente la provincia, la ciudad. Me avisas cualquier novedad, estare atento. 

Gracias

2018-06-05 19:15 UTC, closed without merging